# Simple workflow for deploying static content to a remote server (Ubuntu)
name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master  # Trigger deploy on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install sshpass
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      # Step 2: Ensure the .ssh directory exists and add Raspberry Pi to known_hosts
      - name: Add Raspberry Pi to known_hosts
        run: |
          mkdir -p ~/.ssh  # Create .ssh directory if it doesn't exist
          echo "Adding Raspberry Pi to known_hosts..."
          ssh-keyscan -H "${{ secrets.DEPLOY_SERVER }}" >> ~/.ssh/known_hosts  # Add the server to known_hosts

      # Step 3: Test the SSH connection by creating a file (touch hello.world)
      - name: Test with touch hello.world
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "touch hello.world"
